CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS app_user (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'USER')),
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_app_user_username_ci
    ON app_user (lower(username));

CREATE TABLE IF NOT EXISTS document (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id            BIGINT        NOT NULL,
    title               VARCHAR(300)  NOT NULL,
    document_type       VARCHAR(30)   NOT NULL,

    projects            JSONB         NOT NULL DEFAULT '[]'::jsonb,
    technologies        JSONB         NOT NULL DEFAULT '[]'::jsonb,
    tags                JSONB         NOT NULL DEFAULT '[]'::jsonb,

    source_name         VARCHAR(300),
    source_uri          TEXT,
    media_type          VARCHAR(150)  NOT NULL,
    original_content    BYTEA         NOT NULL,
    occurred_on         DATE,
    content             TEXT          NOT NULL,
    content_hash        VARCHAR(64)   NOT NULL,

    version             INTEGER       NOT NULL DEFAULT 1,
    lock_version        BIGINT        NOT NULL DEFAULT 0,
    indexing_attempt    VARCHAR(36),
    embedding_model     VARCHAR(100),
    indexing_status     VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_document_owner
        FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uq_document_id_owner UNIQUE (id, owner_id),
    CONSTRAINT ck_document_projects_array
        CHECK (jsonb_typeof(projects) = 'array'),
    CONSTRAINT ck_document_technologies_array
        CHECK (jsonb_typeof(technologies) = 'array'),
    CONSTRAINT ck_document_tags_array
        CHECK (jsonb_typeof(tags) = 'array'),
    CONSTRAINT ck_document_version CHECK (version > 0),
    CONSTRAINT ck_document_indexing_status
        CHECK (indexing_status IN ('PENDING', 'READY', 'FAILED'))
);

ALTER TABLE document
    ADD COLUMN IF NOT EXISTS lock_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE document
    ADD COLUMN IF NOT EXISTS indexing_attempt VARCHAR(36);
ALTER TABLE document
    ADD COLUMN IF NOT EXISTS embedding_model VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_document_owner_updated
    ON document (owner_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_document_owner_type
    ON document (owner_id, document_type);
CREATE INDEX IF NOT EXISTS idx_document_owner_occurred
    ON document (owner_id, occurred_on DESC)
    WHERE occurred_on IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_owner_content_hash
    ON document (owner_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_document_reindex
    ON document (owner_id, indexing_status, updated_at)
    WHERE indexing_status <> 'READY';
CREATE INDEX IF NOT EXISTS idx_document_projects_gin
    ON document USING gin (projects);
CREATE INDEX IF NOT EXISTS idx_document_technologies_gin
    ON document USING gin (technologies);
CREATE INDEX IF NOT EXISTS idx_document_tags_gin
    ON document USING gin (tags);

CREATE TABLE IF NOT EXISTS document_chunk (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT        NOT NULL,
    owner_id            BIGINT        NOT NULL,
    document_version    INTEGER       NOT NULL,
    chunk_index         INTEGER       NOT NULL,
    heading             VARCHAR(300),
    content             TEXT          NOT NULL,
    char_count          INTEGER       NOT NULL,
    embedding           vector(1024),
    embedding_model     VARCHAR(100)  NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_document_chunk_document_owner
        FOREIGN KEY (document_id, owner_id)
        REFERENCES document (id, owner_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_document_chunk_position
        UNIQUE (document_id, document_version, chunk_index),
    CONSTRAINT ck_document_chunk_version CHECK (document_version > 0),
    CONSTRAINT ck_document_chunk_index CHECK (chunk_index >= 0),
    CONSTRAINT ck_document_chunk_char_count CHECK (char_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_document_chunk_owner_document_version
    ON document_chunk (owner_id, document_id, document_version);
DROP INDEX IF EXISTS idx_document_chunk_embedding_hnsw;

CREATE TABLE IF NOT EXISTS conversation (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT        NOT NULL,
    title           VARCHAR(160)  NOT NULL,
    next_sequence   BIGINT        NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_conversation_owner
        FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uq_conversation_id_owner UNIQUE (id, owner_id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_owner_updated
    ON conversation (owner_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_message (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT        NOT NULL,
    owner_id            BIGINT        NOT NULL,
    sequence_no         BIGINT        NOT NULL,
    role                VARCHAR(20)   NOT NULL,
    status              VARCHAR(20)   NOT NULL,
    content             TEXT          NOT NULL DEFAULT '',
    sources             JSONB         NOT NULL DEFAULT '[]'::jsonb,
    request_id          VARCHAR(80),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_chat_message_conversation_owner
        FOREIGN KEY (conversation_id, owner_id)
        REFERENCES conversation (id, owner_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_chat_message_sequence
        UNIQUE (conversation_id, sequence_no),
    CONSTRAINT ck_chat_message_role
        CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_chat_message_status
        CHECK (status IN ('COMPLETED', 'GENERATING', 'NO_CONTEXT', 'FAILED')),
    CONSTRAINT ck_chat_message_sources_array
        CHECK (jsonb_typeof(sources) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_chat_message_conversation_created
    ON chat_message (owner_id, conversation_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_chat_message_owner_request
    ON chat_message (owner_id, request_id)
    WHERE request_id IS NOT NULL;
